import Head from 'next/head'
import "tailwindcss/tailwind.css"
import Header from '../components/Header'
import Footer from '../components/Footer'
import Sider from '../components/Sider'
import ProductScreen from '../components/ProductScreen'
import { CartContextProvider } from '@/components/Cartcontext'


export default function Home() {

  return (
    <>
      <Head>
        <title>携程商城</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartContextProvider>
         <Header/>
         <Sider/>
         {/* 商品展示 */}
         <ProductScreen/>
         <Footer/>
      </CartContextProvider>
    </>
  )
}
